services:
  server-client:
    build:
      context: ./
    volumes:
      - ./:/app:z
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres-dev
    networks:
      - app-network-dev

  postgres-dev:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network-dev
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - server-client
    networks:
      - app-network-dev
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network-dev:
    driver: bridge

volumes:
  postgres-dev-data:
